/* The following code was generated by JFlex 1.4.3 on 04.06.14 19:54 */

package neutrino.idea.parsing;

import com.intellij.lexer.FlexLexer;
import com.intellij.psi.tree.IElementType;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 04.06.14 19:54 from the specification file
 * <tt>C:/projects/lepton/neutrino-idea-plugin/src/neutrino/idea/parsing/Literal.flex</tt>
 */
class _LiteralLexer implements FlexLexer {
  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\0"+
    "\1\24\1\51\1\6\2\0\1\25\1\37\1\40\1\5\1\54\1\47"+
    "\1\23\1\21\1\4\1\10\1\16\2\15\4\17\2\11\1\45\1\46"+
    "\1\53\1\0\1\52\1\0\1\50\3\14\1\55\1\22\1\20\5\6"+
    "\1\12\13\6\1\13\2\6\1\43\1\26\1\44\1\0\1\6\1\0"+
    "\1\34\2\14\1\55\1\32\1\33\5\6\1\35\5\6\1\30\1\36"+
    "\1\27\1\31\2\6\1\13\2\6\1\41\1\0\1\42\1\0\41\7"+
    "\2\0\4\6\4\0\1\6\2\0\1\7\7\0\1\6\4\0\1\6"+
    "\5\0\27\6\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0\5\6"+
    "\7\0\1\6\1\0\1\6\21\0\160\7\5\6\1\0\2\6\2\0"+
    "\4\6\10\0\1\6\1\0\3\6\1\0\1\6\1\0\24\6\1\0"+
    "\123\6\1\0\213\6\1\0\5\7\2\0\236\6\11\0\46\6\2\0"+
    "\1\6\7\0\47\6\7\0\1\6\1\0\55\7\1\0\1\7\1\0"+
    "\2\7\1\0\2\7\1\0\1\7\10\0\33\6\5\0\3\6\15\0"+
    "\5\7\6\0\1\6\4\0\13\7\5\0\53\6\37\7\4\0\2\6"+
    "\1\7\143\6\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0"+
    "\4\7\2\6\12\7\3\6\2\0\1\6\17\0\1\7\1\6\1\7"+
    "\36\6\33\7\2\0\131\6\13\7\1\6\16\0\12\7\41\6\11\7"+
    "\2\6\4\0\1\6\5\0\26\6\4\7\1\6\11\7\1\6\3\7"+
    "\1\6\5\7\22\0\31\6\3\7\104\0\1\6\1\0\13\6\67\0"+
    "\33\7\1\0\4\7\66\6\3\7\1\6\22\7\1\6\7\7\12\6"+
    "\2\7\2\0\12\7\1\0\7\6\1\0\7\6\1\0\3\7\1\0"+
    "\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\1\6\3\0"+
    "\4\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7\1\6"+
    "\10\0\1\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7\4\6"+
    "\7\0\1\6\5\0\3\7\1\0\6\6\4\0\2\6\2\0\26\6"+
    "\1\0\7\6\1\0\2\6\1\0\2\6\1\0\2\6\2\0\1\7"+
    "\1\0\5\7\4\0\2\7\2\0\3\7\3\0\1\7\7\0\4\6"+
    "\1\0\1\6\7\0\14\7\3\6\1\7\13\0\3\7\1\0\11\6"+
    "\1\0\3\6\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6"+
    "\2\0\1\7\1\6\10\7\1\0\3\7\1\0\3\7\2\0\1\6"+
    "\17\0\2\6\2\7\2\0\12\7\1\0\1\6\17\0\3\7\1\0"+
    "\10\6\2\0\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0"+
    "\5\6\2\0\1\7\1\6\7\7\2\0\2\7\2\0\3\7\10\0"+
    "\2\7\4\0\2\6\1\0\3\6\2\7\2\0\12\7\1\0\1\6"+
    "\20\0\1\7\1\6\1\0\6\6\3\0\3\6\1\0\4\6\3\0"+
    "\2\6\1\0\1\6\1\0\2\6\3\0\2\6\3\0\3\6\3\0"+
    "\14\6\4\0\5\7\3\0\3\7\1\0\4\7\2\0\1\6\6\0"+
    "\1\7\16\0\12\7\11\0\1\6\7\0\3\7\1\0\10\6\1\0"+
    "\3\6\1\0\27\6\1\0\12\6\1\0\5\6\3\0\1\6\7\7"+
    "\1\0\3\7\1\0\4\7\7\0\2\7\1\0\2\6\6\0\2\6"+
    "\2\7\2\0\12\7\22\0\2\7\1\0\10\6\1\0\3\6\1\0"+
    "\27\6\1\0\12\6\1\0\5\6\2\0\1\7\1\6\7\7\1\0"+
    "\3\7\1\0\4\7\7\0\2\7\7\0\1\6\1\0\2\6\2\7"+
    "\2\0\12\7\1\0\2\6\17\0\2\7\1\0\10\6\1\0\3\6"+
    "\1\0\51\6\2\0\1\6\7\7\1\0\3\7\1\0\4\7\1\6"+
    "\10\0\1\7\10\0\2\6\2\7\2\0\12\7\12\0\6\6\2\0"+
    "\2\7\1\0\22\6\3\0\30\6\1\0\11\6\1\0\1\6\2\0"+
    "\7\6\3\0\1\7\4\0\6\7\1\0\1\7\1\0\10\7\22\0"+
    "\2\7\15\0\60\6\1\7\2\6\7\7\4\0\10\6\10\7\1\0"+
    "\12\7\47\0\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0"+
    "\1\6\6\0\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0"+
    "\1\6\2\0\2\6\1\0\4\6\1\7\2\6\6\7\1\0\2\7"+
    "\1\6\2\0\5\6\1\0\1\6\1\0\6\7\2\0\12\7\2\0"+
    "\4\6\40\0\1\6\27\0\2\7\6\0\12\7\13\0\1\7\1\0"+
    "\1\7\1\0\1\7\4\0\2\7\10\6\1\0\44\6\4\0\24\7"+
    "\1\0\2\7\5\6\13\7\1\0\44\7\11\0\1\7\71\0\53\6"+
    "\24\7\1\6\12\7\6\0\6\6\4\7\4\6\3\7\1\6\3\7"+
    "\2\6\7\7\3\6\4\7\15\6\14\7\1\6\17\7\2\0\46\6"+
    "\1\0\1\6\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0\4\6"+
    "\2\0\7\6\1\0\1\6\1\0\4\6\2\0\51\6\1\0\4\6"+
    "\2\0\41\6\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6"+
    "\2\0\17\6\1\0\71\6\1\0\4\6\2\0\103\6\2\0\3\7"+
    "\40\0\20\6\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0\32\6"+
    "\5\0\113\6\3\0\3\6\17\0\15\6\1\0\4\6\3\7\13\0"+
    "\22\6\3\7\13\0\22\6\2\7\14\0\15\6\1\0\3\6\1\0"+
    "\2\7\14\0\64\6\40\7\3\0\1\6\3\0\2\6\1\7\2\0"+
    "\12\7\41\0\3\7\2\0\12\7\6\0\130\6\10\0\51\6\1\7"+
    "\1\6\5\0\106\6\12\0\35\6\3\0\14\7\4\0\14\7\12\0"+
    "\12\7\36\6\2\0\5\6\13\0\54\6\4\0\21\7\7\6\2\7"+
    "\6\0\12\7\46\0\27\6\5\7\4\0\65\6\12\7\1\0\35\7"+
    "\2\0\13\7\6\0\12\7\15\0\1\6\130\0\5\7\57\6\21\7"+
    "\7\6\4\0\12\7\21\0\11\7\14\0\3\7\36\6\15\7\2\6"+
    "\12\7\54\6\16\7\14\0\44\6\24\7\10\0\12\7\3\0\3\6"+
    "\12\7\44\6\122\0\3\7\1\0\25\7\4\6\1\7\4\6\3\7"+
    "\2\6\11\0\300\6\47\7\25\0\4\7\u0116\6\2\0\6\6\2\0"+
    "\46\6\2\0\6\6\2\0\10\6\1\0\1\6\1\0\1\6\1\0"+
    "\1\6\1\0\37\6\2\0\65\6\1\0\7\6\1\0\1\6\3\0"+
    "\3\6\1\0\7\6\3\0\4\6\2\0\6\6\4\0\15\6\5\0"+
    "\3\6\1\0\7\6\16\0\5\7\32\0\5\7\20\0\2\6\23\0"+
    "\1\6\13\0\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0"+
    "\15\6\3\0\33\6\25\0\15\7\4\0\1\7\3\0\14\7\21\0"+
    "\1\6\4\0\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0"+
    "\1\6\1\0\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0"+
    "\4\6\5\0\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0"+
    "\57\6\1\0\205\6\6\0\4\6\3\7\2\6\14\0\46\6\1\0"+
    "\1\6\5\0\1\6\2\0\70\6\7\0\1\6\17\0\1\7\27\6"+
    "\11\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\40\7\57\0\1\6"+
    "\u01d5\0\3\6\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0"+
    "\126\6\2\0\2\7\2\0\3\6\1\0\132\6\1\0\4\6\5\0"+
    "\51\6\3\0\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0"+
    "\u51cd\6\63\0\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7"+
    "\2\6\24\0\57\6\1\7\4\0\12\7\1\0\31\6\7\0\1\7"+
    "\120\6\2\7\45\0\11\6\2\0\147\6\2\0\4\6\1\0\4\6"+
    "\14\0\13\6\115\0\12\6\1\7\3\6\1\7\4\6\1\7\27\6"+
    "\5\7\20\0\1\6\7\0\64\6\14\0\2\7\62\6\21\7\13\0"+
    "\12\7\6\0\22\7\6\6\3\0\1\6\4\0\12\7\34\6\10\7"+
    "\2\0\27\6\15\7\14\0\35\6\3\0\4\7\57\6\16\7\16\0"+
    "\1\6\12\7\46\0\51\6\16\7\11\0\3\6\1\7\10\6\2\7"+
    "\2\0\12\7\6\0\27\6\3\0\1\6\1\7\4\0\60\6\1\7"+
    "\1\6\3\7\2\6\2\7\5\6\2\7\1\6\1\7\1\6\30\0"+
    "\3\6\2\0\13\6\5\7\2\0\3\6\2\7\12\0\6\6\2\0"+
    "\6\6\2\0\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\7"+
    "\1\0\2\7\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6"+
    "\u2104\0\u016e\6\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6"+
    "\1\7\12\6\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6"+
    "\1\0\2\6\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6"+
    "\50\0\15\6\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6"+
    "\31\0\1\6\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6"+
    "\13\0\12\7\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6"+
    "\3\0\6\6\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6"+
    "\3\0\2\6\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\1\1\1\3\2\4\1\5\1\6"+
    "\1\7\1\10\2\3\1\11\1\12\1\13\1\14\1\15"+
    "\1\16\1\17\1\20\1\21\1\22\1\23\1\24\1\25"+
    "\1\26\1\27\1\0\1\4\1\30\1\31\1\0\3\4"+
    "\1\32\1\30\1\0\1\30\3\7\2\10\2\3\2\27"+
    "\1\0\4\4\1\30\1\0\1\7\1\0\2\3\1\33"+
    "\3\4\1\0\1\34\3\4\1\0\3\4\1\7\14\4"+
    "\1\0\2\4\1\0\2\4\1\0\2\4\1\0\2\4"+
    "\1\0\2\4\1\0\2\4\1\0\1\4\1\30\1\0"+
    "\5\30";

  private static int [] zzUnpackAction() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\56\0\134\0\56\0\212\0\270\0\346\0\u0114"+
    "\0\u0142\0\56\0\u0170\0\u019e\0\u01cc\0\u01fa\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\56\0\56\0\56\0\56"+
    "\0\56\0\56\0\56\0\56\0\u0228\0\u0256\0\u0284\0\u02b2"+
    "\0\56\0\u02e0\0\u030e\0\u033c\0\u036a\0\56\0\u0398\0\u03c6"+
    "\0\56\0\u03f4\0\u0422\0\u0450\0\56\0\u047e\0\u04ac\0\u04da"+
    "\0\u0508\0\56\0\u0536\0\u0564\0\u0592\0\u05c0\0\u05ee\0\u061c"+
    "\0\u064a\0\56\0\u0678\0\u06a6\0\u06d4\0\56\0\u0702\0\u0730"+
    "\0\u075e\0\u078c\0\270\0\u07ba\0\u07e8\0\u0816\0\u0844\0\u0872"+
    "\0\u08a0\0\u08ce\0\u0844\0\u08fc\0\u092a\0\u0958\0\u0986\0\u09b4"+
    "\0\u09e2\0\u0a10\0\u0a3e\0\u0a6c\0\u0a9a\0\u0ac8\0\u0af6\0\u0b24"+
    "\0\u0b52\0\u0b80\0\u0bae\0\u0bdc\0\u0c0a\0\u0c38\0\u0c66\0\u0c94"+
    "\0\u0cc2\0\u0cf0\0\u0d1e\0\u0d4c\0\u0d7a\0\u0da8\0\u0dd6\0\u0e04"+
    "\0\u0e32\0\u0e60\0\u0e8e\0\u0e8e\0\u0ebc\0\u0eea\0\u0f18\0\u0f46"+
    "\0\u0f74\0\u0fa2";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\2\1\6\1\2\1\7"+
    "\1\10\3\6\3\10\1\6\1\11\1\6\1\12\1\13"+
    "\1\14\1\2\1\15\3\6\1\16\3\6\1\17\1\20"+
    "\1\21\1\22\1\23\1\24\1\25\1\26\1\27\1\30"+
    "\1\31\1\32\1\33\1\34\1\6\60\0\1\4\57\0"+
    "\1\35\1\36\56\0\13\6\1\0\1\6\4\0\10\6"+
    "\16\0\1\6\10\0\1\37\1\40\1\41\1\42\1\0"+
    "\1\43\1\44\1\45\1\46\1\47\1\50\7\0\1\50"+
    "\1\46\1\0\1\41\17\0\1\51\10\0\2\10\1\41"+
    "\2\0\3\10\1\46\1\47\1\50\7\0\1\50\1\46"+
    "\1\0\1\41\17\0\1\51\10\0\2\47\3\0\3\47"+
    "\36\0\1\52\2\0\21\52\1\53\1\52\1\54\27\52"+
    "\1\14\2\0\22\14\1\55\1\56\27\14\6\0\13\6"+
    "\1\0\1\6\4\0\1\6\1\57\6\6\16\0\1\6"+
    "\6\0\13\6\1\0\1\6\4\0\5\6\1\60\2\6"+
    "\16\0\1\6\1\35\1\61\1\62\53\35\5\36\1\63"+
    "\50\36\10\0\1\37\1\40\1\41\2\0\1\43\1\44"+
    "\1\45\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\40\3\0\3\40\1\46"+
    "\1\47\1\50\7\0\1\50\1\46\21\0\1\51\10\0"+
    "\1\64\1\65\2\0\5\65\1\0\1\65\7\0\3\65"+
    "\20\0\1\65\10\0\1\66\1\40\1\41\2\0\3\66"+
    "\1\46\1\47\1\50\7\0\1\50\1\46\1\0\1\41"+
    "\17\0\1\51\10\0\1\45\1\40\1\41\2\0\3\45"+
    "\1\46\1\47\1\50\7\0\1\50\1\46\1\0\1\41"+
    "\17\0\1\51\10\0\1\67\1\40\1\41\2\0\3\67"+
    "\1\46\1\47\1\50\7\0\1\50\1\46\1\0\1\41"+
    "\17\0\1\51\10\0\2\47\3\0\3\47\1\46\1\0"+
    "\1\50\7\0\1\50\1\46\21\0\1\51\10\0\2\70"+
    "\3\0\3\70\3\0\1\71\30\0\1\71\1\0\1\52"+
    "\2\0\21\52\1\72\1\52\1\54\27\52\24\0\1\73"+
    "\31\0\1\52\2\0\53\52\1\14\2\0\53\14\6\0"+
    "\13\6\1\0\1\6\4\0\2\6\1\74\5\6\16\0"+
    "\1\6\6\0\13\6\1\0\1\6\4\0\6\6\1\75"+
    "\1\6\16\0\1\6\2\0\1\62\53\0\4\36\1\76"+
    "\1\63\50\36\10\0\1\64\1\65\1\41\1\0\5\65"+
    "\1\0\1\65\7\0\3\65\1\41\17\0\1\65\10\0"+
    "\2\77\1\41\1\0\5\77\1\0\1\77\7\0\3\77"+
    "\1\41\17\0\1\77\10\0\1\100\1\40\1\41\2\0"+
    "\3\100\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\101\1\40\1\41\2\0"+
    "\3\101\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\70\3\0\3\70\1\46"+
    "\12\0\1\46\21\0\1\51\10\0\2\70\3\0\3\70"+
    "\36\0\5\73\1\0\16\73\1\102\31\73\6\0\13\6"+
    "\1\0\1\6\4\0\3\6\1\103\4\6\16\0\1\6"+
    "\6\0\13\6\1\0\1\6\4\0\7\6\1\74\16\0"+
    "\1\6\10\0\2\104\1\41\1\0\5\104\1\0\1\104"+
    "\7\0\3\104\1\41\17\0\1\104\10\0\1\105\1\40"+
    "\1\41\2\0\3\105\1\46\1\47\1\50\7\0\1\50"+
    "\1\46\1\0\1\41\17\0\1\51\10\0\1\106\1\40"+
    "\1\41\2\0\3\106\1\46\1\47\1\50\7\0\1\50"+
    "\1\46\1\0\1\41\17\0\1\51\5\73\1\0\16\73"+
    "\1\107\31\73\10\0\2\110\1\41\1\0\5\110\1\0"+
    "\1\110\7\0\3\110\1\41\17\0\1\110\10\0\1\111"+
    "\1\40\1\41\2\0\3\111\1\46\1\47\1\50\7\0"+
    "\1\50\1\46\1\0\1\41\17\0\1\51\10\0\1\112"+
    "\1\40\1\41\2\0\3\112\1\46\1\47\1\50\7\0"+
    "\1\50\1\46\1\0\1\41\17\0\1\51\5\73\1\0"+
    "\16\73\1\113\31\73\10\0\2\114\1\41\1\0\5\114"+
    "\1\0\1\114\7\0\3\114\1\41\17\0\1\114\10\0"+
    "\1\115\1\40\1\41\2\0\3\115\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\116\1\40\1\41\2\0\3\116\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\117\1\41\1\0\5\117\1\0\1\117\7\0\3\117"+
    "\1\41\17\0\1\117\10\0\1\120\1\40\1\41\2\0"+
    "\3\120\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\121\1\40\1\41\2\0"+
    "\3\121\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\122\1\41\1\0\5\122"+
    "\1\0\1\122\7\0\3\122\1\41\17\0\1\122\10\0"+
    "\1\123\1\40\1\41\2\0\3\123\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\124\1\40\1\41\2\0\3\124\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\125\1\41\1\0\5\125\1\0\1\125\7\0\3\125"+
    "\1\41\17\0\1\125\10\0\1\126\1\40\1\41\2\0"+
    "\3\126\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\127\1\40\1\41\2\0"+
    "\3\127\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\130\1\41\1\0\5\130"+
    "\1\0\1\130\7\0\3\130\1\41\17\0\1\130\10\0"+
    "\1\131\1\40\1\41\2\0\3\131\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\132\1\40\1\41\2\0\3\132\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\133\1\41\1\0\5\133\1\0\1\133\7\0\3\133"+
    "\1\41\17\0\1\133\10\0\1\134\1\40\1\41\2\0"+
    "\3\134\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\135\1\40\1\41\2\0"+
    "\3\135\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\136\1\41\1\0\5\136"+
    "\1\0\1\136\7\0\3\136\1\41\17\0\1\136\10\0"+
    "\1\137\1\40\1\41\2\0\3\137\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\140\1\40\1\41\2\0\3\140\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\141\1\41\1\0\5\141\1\0\1\141\7\0\3\141"+
    "\1\41\17\0\1\141\10\0\1\142\1\40\1\41\2\0"+
    "\3\142\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\143\1\40\1\41\2\0"+
    "\3\143\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\144\1\41\1\0\5\144"+
    "\1\0\1\144\7\0\3\144\1\41\17\0\1\144\10\0"+
    "\1\145\1\40\1\41\2\0\3\145\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\146\1\40\1\41\2\0\3\146\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\147\1\41\1\0\5\147\1\0\1\147\7\0\3\147"+
    "\1\41\17\0\1\147\10\0\1\150\1\40\1\41\2\0"+
    "\3\150\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\1\151\1\40\1\41\2\0"+
    "\3\151\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\10\0\2\152\1\41\1\0\5\152"+
    "\1\0\1\152\7\0\3\152\1\41\17\0\1\152\10\0"+
    "\1\153\1\40\1\41\2\0\3\153\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\154\1\40\1\41\2\0\3\154\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\155\1\41\1\0\5\155\1\0\1\155\7\0\3\155"+
    "\1\41\17\0\1\155\10\0\1\156\1\40\1\41\2\0"+
    "\3\156\1\46\1\47\1\50\7\0\1\50\1\46\1\0"+
    "\1\41\17\0\1\51\12\0\1\41\22\0\1\41\30\0"+
    "\1\157\1\40\1\41\2\0\3\157\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\160\1\40\1\41\2\0\3\160\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\161\1\40\1\41\2\0\3\161\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\1\162\1\40\1\41\2\0\3\162\1\46\1\47\1\50"+
    "\7\0\1\50\1\46\1\0\1\41\17\0\1\51\10\0"+
    "\2\40\1\41\2\0\3\40\1\46\1\47\1\50\7\0"+
    "\1\50\1\46\1\0\1\41\17\0\1\51";

  private static int [] zzUnpackTrans() {
    int [] result = new int[4048];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;
  private static final char[] EMPTY_BUFFER = new char[0];
  private static final int YYEOF = -1;
  private static java.io.Reader zzReader = null; // Fake

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\1\11\5\1\1\11\4\1\16\11"+
    "\1\1\1\0\2\1\1\11\1\0\3\1\1\11\1\1"+
    "\1\0\1\11\3\1\1\11\4\1\1\11\1\0\5\1"+
    "\1\0\1\11\1\0\2\1\1\11\3\1\1\0\4\1"+
    "\1\0\20\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[114];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private CharSequence zzBuffer = "";

  /** this buffer may contains the current text array to be matched when it is cheap to acquire it */
  private char[] zzBufferArray;

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the textposition at the last state to be included in yytext */
  private int zzPushbackPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /**
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;


  _LiteralLexer(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  _LiteralLexer(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2250) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }

  public final int getTokenStart(){
    return zzStartRead;
  }

  public final int getTokenEnd(){
    return getTokenStart() + yylength();
  }

  public void reset(CharSequence buffer, int start, int end,int initialState){
    zzBuffer = buffer;
    zzBufferArray = com.intellij.util.text.CharArrayUtil.fromSequenceWithoutCopying(buffer);
    zzCurrentPos = zzMarkedPos = zzStartRead = start;
    zzPushbackPos = 0;
    zzAtEOF  = false;
    zzAtBOL = true;
    zzEndRead = end;
    yybegin(initialState);
  }

  // For Demetra compatibility
  public void reset(CharSequence buffer, int initialState){
    zzBuffer = buffer;
    zzBufferArray = null; 
    zzCurrentPos = zzMarkedPos = zzStartRead = 0;
    zzPushbackPos = 0;
    zzAtEOF = false;
    zzAtBOL = true;
    zzEndRead = buffer.length();
    yybegin(initialState);
  }

  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   *
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {
    return true;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final CharSequence yytext() {
    return zzBuffer.subSequence(zzStartRead, zzMarkedPos);
  }


  /**
   * Returns the character at position <tt>pos</tt> from the
   * matched text.
   *
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch.
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBufferArray != null ? zzBufferArray[zzStartRead+pos]:zzBuffer.charAt(zzStartRead+pos);
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of
   * yypushback(int) and a match-all fallback rule) this method
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() {
    if (!zzEOFDone) {
      zzEOFDone = true;
    
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public IElementType advance() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    CharSequence zzBufferL = zzBuffer;
    char[] zzBufferArrayL = zzBufferArray;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL.charAt(zzCurrentPosL++);
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL.charAt(zzCurrentPosL++);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 25: 
          { return LiteralTokenTypes.LONG_LITERAL;
          }
        case 29: break;
        case 16: 
          { return LiteralTokenTypes.SEMICOLON;
          }
        case 30: break;
        case 28: 
          { return LiteralTokenTypes.BOOLEAN_LITERAL;
          }
        case 31: break;
        case 1: 
          { return com.intellij.psi.TokenType.BAD_CHARACTER;
          }
        case 32: break;
        case 12: 
          { return LiteralTokenTypes.RBRACE;
          }
        case 33: break;
        case 17: 
          { return LiteralTokenTypes.COMMA;
          }
        case 34: break;
        case 14: 
          { return LiteralTokenTypes.RBRACK;
          }
        case 35: break;
        case 2: 
          { return LiteralTokenTypes.WHITE_SPACE;
          }
        case 36: break;
        case 27: 
          { return LiteralTokenTypes.BLOCK_COMMENT;
          }
        case 37: break;
        case 24: 
          { return LiteralTokenTypes.DOUBLE_LITERAL;
          }
        case 38: break;
        case 18: 
          { return LiteralTokenTypes.AT;
          }
        case 39: break;
        case 23: 
          { return LiteralTokenTypes.END_OF_LINE_COMMENT;
          }
        case 40: break;
        case 3: 
          { return LiteralTokenTypes.IDENTIFIER;
          }
        case 41: break;
        case 8: 
          { return neutrino.idea.parsing.LiteralElementTypes.CHAR_LITERAL;
          }
        case 42: break;
        case 21: 
          { return LiteralTokenTypes.LT;
          }
        case 43: break;
        case 6: 
          { return LiteralTokenTypes.MINUS;
          }
        case 44: break;
        case 26: 
          { return LiteralTokenTypes.FLOAT_LITERAL;
          }
        case 45: break;
        case 22: 
          { return LiteralTokenTypes.PLUS;
          }
        case 46: break;
        case 7: 
          { return neutrino.idea.parsing.LiteralElementTypes.STRING_LITERAL;
          }
        case 47: break;
        case 11: 
          { return LiteralTokenTypes.LBRACE;
          }
        case 48: break;
        case 4: 
          { return LiteralTokenTypes.INTEGER_LITERAL;
          }
        case 49: break;
        case 9: 
          { return LiteralTokenTypes.LPAREN;
          }
        case 50: break;
        case 5: 
          { return LiteralTokenTypes.DOT;
          }
        case 51: break;
        case 13: 
          { return LiteralTokenTypes.LBRACK;
          }
        case 52: break;
        case 15: 
          { return LiteralTokenTypes.COLON;
          }
        case 53: break;
        case 19: 
          { return LiteralTokenTypes.POUND;
          }
        case 54: break;
        case 10: 
          { return LiteralTokenTypes.RPAREN;
          }
        case 55: break;
        case 20: 
          { return LiteralTokenTypes.GT;
          }
        case 56: break;
        default:
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            zzDoEOF();
            return null;
          }
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
