/* The following code was generated by JFlex 1.4.3 on 15.05.14 13:39 */

/*
 * run with: java -cp JFlex.jar JFlex.Main (this file)
 */
package neutrino.parser;
import static neutrino.parser.LiteralElementTypes.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.4.3
 * on 15.05.14 13:39 from the specification file
 * <tt>C:/projects/lepton/neutrino/src/neutrino/parser/Literal.lex</tt>
 */
public class Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int STRING = 2;
  public static final int YYINITIAL = 0;
  public static final int CHARLITERAL = 4;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0,  0,  1,  1,  2, 2
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\7\1\3\1\2\1\0\1\3\1\1\16\7\4\0\1\3\1\0"+
    "\1\24\1\51\1\6\2\0\1\25\1\37\1\40\1\5\1\23\1\47"+
    "\1\54\1\21\1\4\1\10\1\16\1\55\1\15\1\56\1\17\1\61"+
    "\1\57\1\60\1\11\1\45\1\46\1\53\1\0\1\52\1\0\1\50"+
    "\3\14\1\62\1\22\1\20\5\6\1\12\13\6\1\13\2\6\1\43"+
    "\1\26\1\44\1\0\1\6\1\0\1\34\1\63\1\14\1\62\1\32"+
    "\1\33\5\6\1\35\1\6\1\64\3\6\1\30\1\36\1\27\1\31"+
    "\2\6\1\13\2\6\1\41\1\0\1\42\1\0\41\7\2\0\4\6"+
    "\4\0\1\6\2\0\1\7\7\0\1\6\4\0\1\6\5\0\27\6"+
    "\1\0\37\6\1\0\u01ca\6\4\0\14\6\16\0\5\6\7\0\1\6"+
    "\1\0\1\6\21\0\160\7\5\6\1\0\2\6\2\0\4\6\10\0"+
    "\1\6\1\0\3\6\1\0\1\6\1\0\24\6\1\0\123\6\1\0"+
    "\213\6\1\0\5\7\2\0\236\6\11\0\46\6\2\0\1\6\7\0"+
    "\47\6\7\0\1\6\1\0\55\7\1\0\1\7\1\0\2\7\1\0"+
    "\2\7\1\0\1\7\10\0\33\6\5\0\3\6\15\0\5\7\6\0"+
    "\1\6\4\0\13\7\5\0\53\6\37\7\4\0\2\6\1\7\143\6"+
    "\1\0\1\6\10\7\1\0\6\7\2\6\2\7\1\0\4\7\2\6"+
    "\12\7\3\6\2\0\1\6\17\0\1\7\1\6\1\7\36\6\33\7"+
    "\2\0\131\6\13\7\1\6\16\0\12\7\41\6\11\7\2\6\4\0"+
    "\1\6\5\0\26\6\4\7\1\6\11\7\1\6\3\7\1\6\5\7"+
    "\22\0\31\6\3\7\104\0\1\6\1\0\13\6\67\0\33\7\1\0"+
    "\4\7\66\6\3\7\1\6\22\7\1\6\7\7\12\6\2\7\2\0"+
    "\12\7\1\0\7\6\1\0\7\6\1\0\3\7\1\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\1\6\3\0\4\6\2\0"+
    "\1\7\1\6\7\7\2\0\2\7\2\0\3\7\1\6\10\0\1\7"+
    "\4\0\2\6\1\0\3\6\2\7\2\0\12\7\4\6\7\0\1\6"+
    "\5\0\3\7\1\0\6\6\4\0\2\6\2\0\26\6\1\0\7\6"+
    "\1\0\2\6\1\0\2\6\1\0\2\6\2\0\1\7\1\0\5\7"+
    "\4\0\2\7\2\0\3\7\3\0\1\7\7\0\4\6\1\0\1\6"+
    "\7\0\14\7\3\6\1\7\13\0\3\7\1\0\11\6\1\0\3\6"+
    "\1\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0\1\7"+
    "\1\6\10\7\1\0\3\7\1\0\3\7\2\0\1\6\17\0\2\6"+
    "\2\7\2\0\12\7\1\0\1\6\17\0\3\7\1\0\10\6\2\0"+
    "\2\6\2\0\26\6\1\0\7\6\1\0\2\6\1\0\5\6\2\0"+
    "\1\7\1\6\7\7\2\0\2\7\2\0\3\7\10\0\2\7\4\0"+
    "\2\6\1\0\3\6\2\7\2\0\12\7\1\0\1\6\20\0\1\7"+
    "\1\6\1\0\6\6\3\0\3\6\1\0\4\6\3\0\2\6\1\0"+
    "\1\6\1\0\2\6\3\0\2\6\3\0\3\6\3\0\14\6\4\0"+
    "\5\7\3\0\3\7\1\0\4\7\2\0\1\6\6\0\1\7\16\0"+
    "\12\7\11\0\1\6\7\0\3\7\1\0\10\6\1\0\3\6\1\0"+
    "\27\6\1\0\12\6\1\0\5\6\3\0\1\6\7\7\1\0\3\7"+
    "\1\0\4\7\7\0\2\7\1\0\2\6\6\0\2\6\2\7\2\0"+
    "\12\7\22\0\2\7\1\0\10\6\1\0\3\6\1\0\27\6\1\0"+
    "\12\6\1\0\5\6\2\0\1\7\1\6\7\7\1\0\3\7\1\0"+
    "\4\7\7\0\2\7\7\0\1\6\1\0\2\6\2\7\2\0\12\7"+
    "\1\0\2\6\17\0\2\7\1\0\10\6\1\0\3\6\1\0\51\6"+
    "\2\0\1\6\7\7\1\0\3\7\1\0\4\7\1\6\10\0\1\7"+
    "\10\0\2\6\2\7\2\0\12\7\12\0\6\6\2\0\2\7\1\0"+
    "\22\6\3\0\30\6\1\0\11\6\1\0\1\6\2\0\7\6\3\0"+
    "\1\7\4\0\6\7\1\0\1\7\1\0\10\7\22\0\2\7\15\0"+
    "\60\6\1\7\2\6\7\7\4\0\10\6\10\7\1\0\12\7\47\0"+
    "\2\6\1\0\1\6\2\0\2\6\1\0\1\6\2\0\1\6\6\0"+
    "\4\6\1\0\7\6\1\0\3\6\1\0\1\6\1\0\1\6\2\0"+
    "\2\6\1\0\4\6\1\7\2\6\6\7\1\0\2\7\1\6\2\0"+
    "\5\6\1\0\1\6\1\0\6\7\2\0\12\7\2\0\4\6\40\0"+
    "\1\6\27\0\2\7\6\0\12\7\13\0\1\7\1\0\1\7\1\0"+
    "\1\7\4\0\2\7\10\6\1\0\44\6\4\0\24\7\1\0\2\7"+
    "\5\6\13\7\1\0\44\7\11\0\1\7\71\0\53\6\24\7\1\6"+
    "\12\7\6\0\6\6\4\7\4\6\3\7\1\6\3\7\2\6\7\7"+
    "\3\6\4\7\15\6\14\7\1\6\17\7\2\0\46\6\1\0\1\6"+
    "\5\0\1\6\2\0\53\6\1\0\u014d\6\1\0\4\6\2\0\7\6"+
    "\1\0\1\6\1\0\4\6\2\0\51\6\1\0\4\6\2\0\41\6"+
    "\1\0\4\6\2\0\7\6\1\0\1\6\1\0\4\6\2\0\17\6"+
    "\1\0\71\6\1\0\4\6\2\0\103\6\2\0\3\7\40\0\20\6"+
    "\20\0\125\6\14\0\u026c\6\2\0\21\6\1\0\32\6\5\0\113\6"+
    "\3\0\3\6\17\0\15\6\1\0\4\6\3\7\13\0\22\6\3\7"+
    "\13\0\22\6\2\7\14\0\15\6\1\0\3\6\1\0\2\7\14\0"+
    "\64\6\40\7\3\0\1\6\3\0\2\6\1\7\2\0\12\7\41\0"+
    "\3\7\2\0\12\7\6\0\130\6\10\0\51\6\1\7\1\6\5\0"+
    "\106\6\12\0\35\6\3\0\14\7\4\0\14\7\12\0\12\7\36\6"+
    "\2\0\5\6\13\0\54\6\4\0\21\7\7\6\2\7\6\0\12\7"+
    "\46\0\27\6\5\7\4\0\65\6\12\7\1\0\35\7\2\0\13\7"+
    "\6\0\12\7\15\0\1\6\130\0\5\7\57\6\21\7\7\6\4\0"+
    "\12\7\21\0\11\7\14\0\3\7\36\6\15\7\2\6\12\7\54\6"+
    "\16\7\14\0\44\6\24\7\10\0\12\7\3\0\3\6\12\7\44\6"+
    "\122\0\3\7\1\0\25\7\4\6\1\7\4\6\3\7\2\6\11\0"+
    "\300\6\47\7\25\0\4\7\u0116\6\2\0\6\6\2\0\46\6\2\0"+
    "\6\6\2\0\10\6\1\0\1\6\1\0\1\6\1\0\1\6\1\0"+
    "\37\6\2\0\65\6\1\0\7\6\1\0\1\6\3\0\3\6\1\0"+
    "\7\6\3\0\4\6\2\0\6\6\4\0\15\6\5\0\3\6\1\0"+
    "\7\6\16\0\5\7\32\0\5\7\20\0\2\6\23\0\1\6\13\0"+
    "\5\7\5\0\6\7\1\0\1\6\15\0\1\6\20\0\15\6\3\0"+
    "\33\6\25\0\15\7\4\0\1\7\3\0\14\7\21\0\1\6\4\0"+
    "\1\6\2\0\12\6\1\0\1\6\3\0\5\6\6\0\1\6\1\0"+
    "\1\6\1\0\1\6\1\0\4\6\1\0\13\6\2\0\4\6\5\0"+
    "\5\6\4\0\1\6\21\0\51\6\u0a77\0\57\6\1\0\57\6\1\0"+
    "\205\6\6\0\4\6\3\7\2\6\14\0\46\6\1\0\1\6\5\0"+
    "\1\6\2\0\70\6\7\0\1\6\17\0\1\7\27\6\11\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6\1\0\7\6"+
    "\1\0\7\6\1\0\7\6\1\0\40\7\57\0\1\6\u01d5\0\3\6"+
    "\31\0\11\6\6\7\1\0\5\6\2\0\5\6\4\0\126\6\2\0"+
    "\2\7\2\0\3\6\1\0\132\6\1\0\4\6\5\0\51\6\3\0"+
    "\136\6\21\0\33\6\65\0\20\6\u0200\0\u19b6\6\112\0\u51cd\6\63\0"+
    "\u048d\6\103\0\56\6\2\0\u010d\6\3\0\20\6\12\7\2\6\24\0"+
    "\57\6\1\7\4\0\12\7\1\0\31\6\7\0\1\7\120\6\2\7"+
    "\45\0\11\6\2\0\147\6\2\0\4\6\1\0\4\6\14\0\13\6"+
    "\115\0\12\6\1\7\3\6\1\7\4\6\1\7\27\6\5\7\20\0"+
    "\1\6\7\0\64\6\14\0\2\7\62\6\21\7\13\0\12\7\6\0"+
    "\22\7\6\6\3\0\1\6\4\0\12\7\34\6\10\7\2\0\27\6"+
    "\15\7\14\0\35\6\3\0\4\7\57\6\16\7\16\0\1\6\12\7"+
    "\46\0\51\6\16\7\11\0\3\6\1\7\10\6\2\7\2\0\12\7"+
    "\6\0\27\6\3\0\1\6\1\7\4\0\60\6\1\7\1\6\3\7"+
    "\2\6\2\7\5\6\2\7\1\6\1\7\1\6\30\0\3\6\2\0"+
    "\13\6\5\7\2\0\3\6\2\7\12\0\6\6\2\0\6\6\2\0"+
    "\6\6\11\0\7\6\1\0\7\6\221\0\43\6\10\7\1\0\2\7"+
    "\2\0\12\7\6\0\u2ba4\6\14\0\27\6\4\0\61\6\u2104\0\u016e\6"+
    "\2\0\152\6\46\0\7\6\14\0\5\6\5\0\1\6\1\7\12\6"+
    "\1\0\15\6\1\0\5\6\1\0\1\6\1\0\2\6\1\0\2\6"+
    "\1\0\154\6\41\0\u016b\6\22\0\100\6\2\0\66\6\50\0\15\6"+
    "\3\0\20\7\20\0\7\7\14\0\2\6\30\0\3\6\31\0\1\6"+
    "\6\0\5\6\1\0\207\6\2\0\1\7\4\0\1\6\13\0\12\7"+
    "\7\0\32\6\4\0\1\6\1\0\32\6\13\0\131\6\3\0\6\6"+
    "\2\0\6\6\2\0\6\6\2\0\3\6\3\0\2\6\3\0\2\6"+
    "\22\0\3\7\4\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\3\0\1\1\2\2\1\1\1\3\2\4\1\5\1\1"+
    "\1\6\1\7\2\3\1\10\1\11\1\12\1\13\1\14"+
    "\1\15\1\16\1\17\1\20\1\21\1\22\1\23\1\24"+
    "\1\1\1\25\2\26\1\27\2\1\2\30\1\1\1\2"+
    "\1\0\1\31\1\32\1\33\1\0\3\31\1\34\1\32"+
    "\1\0\1\35\1\4\1\0\2\3\1\4\1\36\2\37"+
    "\1\40\1\41\1\42\1\43\1\44\1\45\1\46\1\47"+
    "\1\50\12\36\1\0\1\51\2\52\2\31\1\32\1\0"+
    "\2\3\1\4\1\37\1\0\1\53\1\0\1\54\1\55"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\1\64\1\52"+
    "\2\31\1\65\1\3\1\4\1\52\2\31\1\66\1\4"+
    "\1\52\2\31\1\4\1\52\2\31\1\4\1\52\2\31"+
    "\1\4\1\52\2\31\1\4\1\52\2\31\1\4\1\0"+
    "\2\31\1\67\1\0\2\31\1\0\2\31\1\0\2\31"+
    "\1\0\2\31\1\0\2\31\1\0\1\31\1\32\1\0"+
    "\5\32";

  private static int [] zzUnpackAction() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\65\0\152\0\237\0\324\0\237\0\u0109\0\u013e"+
    "\0\u0173\0\u01a8\0\u01dd\0\u0212\0\237\0\237\0\u0247\0\u027c"+
    "\0\237\0\237\0\237\0\237\0\237\0\237\0\237\0\237"+
    "\0\237\0\237\0\237\0\237\0\237\0\u02b1\0\u02e6\0\u031b"+
    "\0\237\0\237\0\u0350\0\u0385\0\u03ba\0\237\0\u03ef\0\u0424"+
    "\0\u0459\0\u048e\0\u04c3\0\237\0\u04f8\0\u052d\0\u0562\0\u0597"+
    "\0\237\0\u05cc\0\u0601\0\237\0\u0636\0\u01dd\0\u066b\0\u06a0"+
    "\0\u06d5\0\237\0\u070a\0\u073f\0\237\0\237\0\237\0\237"+
    "\0\237\0\237\0\237\0\237\0\237\0\u0774\0\u07a9\0\u07de"+
    "\0\u0813\0\u0848\0\u087d\0\u08b2\0\u08e7\0\u091c\0\u0951\0\u0986"+
    "\0\237\0\u09bb\0\u09f0\0\u0a25\0\u0a5a\0\u0a8f\0\u0ac4\0\u0af9"+
    "\0\u0b2e\0\u0b63\0\237\0\u07a9\0\237\0\u0b98\0\237\0\237"+
    "\0\237\0\237\0\237\0\237\0\237\0\237\0\237\0\u0bcd"+
    "\0\u0c02\0\u0c37\0\u013e\0\u0c6c\0\u0ca1\0\u0cd6\0\u0d0b\0\u0d40"+
    "\0\u013e\0\u0d75\0\u0daa\0\u0ddf\0\u0e14\0\u0e49\0\u0e7e\0\u0eb3"+
    "\0\u0ee8\0\u0f1d\0\u0f52\0\u0f87\0\u0fbc\0\u0ff1\0\u1026\0\u105b"+
    "\0\u1090\0\u10c5\0\u10fa\0\u112f\0\u1164\0\u1199\0\u11ce\0\u1203"+
    "\0\u1238\0\u01a8\0\u126d\0\u12a2\0\u12d7\0\u130c\0\u1341\0\u1376"+
    "\0\u13ab\0\u13e0\0\u1415\0\u144a\0\u147f\0\u14b4\0\u14e9\0\u151e"+
    "\0\u1553\0\u1588\0\u15bd\0\u15bd\0\u15f2\0\u1627\0\u165c\0\u1691"+
    "\0\u16c6\0\u16fb";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\4\1\5\2\6\1\7\1\4\1\10\1\4\1\11"+
    "\1\12\3\10\3\12\1\10\1\13\1\10\1\14\1\15"+
    "\1\16\1\4\1\17\3\10\1\20\3\10\1\21\1\22"+
    "\1\23\1\24\1\25\1\26\1\27\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\5\12\3\10\1\37\1\40"+
    "\1\41\21\37\1\42\1\37\1\43\36\37\1\44\1\45"+
    "\1\46\22\44\1\4\1\47\36\44\67\0\1\6\66\0"+
    "\1\50\1\51\65\0\13\10\1\0\1\10\4\0\10\10"+
    "\16\0\10\10\10\0\1\52\1\53\1\54\1\55\1\0"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\54\17\0\1\56\2\60\1\53\1\60"+
    "\1\64\12\0\2\12\1\54\2\0\3\12\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\54\17\0\5\12"+
    "\1\64\12\0\2\62\3\0\3\62\35\0\5\62\13\0"+
    "\1\65\1\12\3\0\3\12\1\0\1\66\33\0\5\12"+
    "\11\0\13\10\1\0\1\10\4\0\1\10\1\67\6\10"+
    "\16\0\10\10\6\0\13\10\1\0\1\10\4\0\5\10"+
    "\1\70\2\10\16\0\10\10\10\0\1\65\1\12\3\0"+
    "\3\12\1\0\1\66\33\0\1\71\4\12\3\0\1\37"+
    "\2\0\21\37\1\0\1\37\1\0\36\37\2\0\1\41"+
    "\62\0\2\72\1\0\5\72\1\73\4\72\2\73\1\74"+
    "\4\72\1\75\1\76\1\77\1\100\1\101\2\72\1\102"+
    "\21\72\1\73\2\74\1\72\1\74\1\72\1\103\1\104"+
    "\25\0\1\105\41\0\1\46\62\0\2\72\1\0\5\72"+
    "\1\106\4\72\2\106\1\107\4\72\1\110\1\111\1\112"+
    "\1\113\1\114\2\72\1\115\21\72\1\106\2\107\1\72"+
    "\1\107\1\72\1\116\1\117\1\50\1\5\1\6\62\50"+
    "\5\51\1\120\57\51\10\0\1\52\1\53\1\121\2\0"+
    "\1\56\1\57\1\60\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\121\17\0\1\56\2\60\1\53\1\60"+
    "\1\64\12\0\2\53\3\0\3\53\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\21\0\5\53\1\64\12\0\1\122"+
    "\1\123\2\0\5\123\1\0\1\123\7\0\3\123\20\0"+
    "\7\123\11\0\1\124\1\53\1\121\2\0\3\124\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\124\1\53\1\124\1\64\12\0\1\60\1\53\1\121"+
    "\2\0\3\60\1\61\1\62\1\63\7\0\1\63\1\61"+
    "\1\0\1\121\17\0\3\60\1\53\1\60\1\64\12\0"+
    "\1\125\1\53\1\121\2\0\3\125\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\121\17\0\3\125\1\53"+
    "\1\125\1\64\12\0\2\62\3\0\3\62\1\61\1\0"+
    "\1\63\7\0\1\63\1\61\21\0\5\62\1\64\12\0"+
    "\2\126\3\0\3\126\3\0\1\127\30\0\1\127\5\126"+
    "\13\0\2\53\1\54\2\0\3\53\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\54\17\0\5\53\1\64"+
    "\10\0\13\10\1\0\1\10\4\0\2\10\1\130\5\10"+
    "\16\0\10\10\6\0\13\10\1\0\1\10\4\0\6\10"+
    "\1\131\1\10\16\0\10\10\10\0\2\12\1\54\2\0"+
    "\1\12\1\132\1\12\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\54\17\0\5\12\1\64\12\0\1\74"+
    "\4\0\3\74\35\0\3\74\1\0\1\74\13\0\1\133"+
    "\4\0\3\133\35\0\3\133\1\0\1\133\13\0\1\134"+
    "\4\0\3\134\5\0\1\135\27\0\3\134\1\0\1\134"+
    "\13\0\1\136\4\0\3\136\5\0\1\135\27\0\3\136"+
    "\1\0\1\136\30\0\1\137\64\0\1\140\64\0\1\141"+
    "\64\0\1\142\64\0\1\143\64\0\1\144\64\0\1\145"+
    "\64\0\1\146\37\0\4\51\1\6\1\120\57\51\10\0"+
    "\1\122\1\123\1\147\1\0\5\123\1\0\1\123\7\0"+
    "\3\123\1\147\17\0\7\123\11\0\2\150\1\147\1\0"+
    "\5\150\1\0\1\150\7\0\3\150\1\147\17\0\7\150"+
    "\11\0\1\151\1\53\1\121\2\0\3\151\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\121\17\0\3\151"+
    "\1\53\1\151\1\64\12\0\1\152\1\53\1\121\2\0"+
    "\3\152\1\61\1\62\1\63\7\0\1\63\1\61\1\0"+
    "\1\121\17\0\3\152\1\53\1\152\1\64\12\0\2\126"+
    "\3\0\3\126\1\61\12\0\1\61\21\0\5\126\1\64"+
    "\12\0\2\126\3\0\3\126\35\0\5\126\11\0\13\10"+
    "\1\0\1\10\4\0\3\10\1\153\4\10\16\0\10\10"+
    "\6\0\13\10\1\0\1\10\4\0\7\10\1\154\16\0"+
    "\10\10\10\0\2\12\1\54\2\0\3\12\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\54\17\0\1\12"+
    "\1\155\3\12\1\64\27\0\1\135\47\0\2\156\1\147"+
    "\1\0\5\156\1\0\1\156\7\0\3\156\1\147\17\0"+
    "\7\156\11\0\1\157\1\53\1\121\2\0\3\157\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\157\1\53\1\157\1\64\12\0\1\160\1\53\1\121"+
    "\2\0\3\160\1\61\1\62\1\63\7\0\1\63\1\61"+
    "\1\0\1\121\17\0\3\160\1\53\1\160\1\64\10\0"+
    "\13\10\1\0\1\10\4\0\3\10\1\161\4\10\16\0"+
    "\10\10\10\0\2\12\1\54\2\0\3\12\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\54\17\0\2\12"+
    "\1\162\2\12\1\64\12\0\2\163\1\147\1\0\5\163"+
    "\1\0\1\163\7\0\3\163\1\147\17\0\7\163\11\0"+
    "\1\164\1\53\1\121\2\0\3\164\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\121\17\0\3\164\1\53"+
    "\1\164\1\64\12\0\1\165\1\53\1\121\2\0\3\165"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\121"+
    "\17\0\3\165\1\53\1\165\1\64\12\0\2\12\1\54"+
    "\2\0\3\12\1\61\1\62\1\63\7\0\1\63\1\61"+
    "\1\0\1\54\17\0\1\12\1\166\3\12\1\64\12\0"+
    "\2\167\1\147\1\0\5\167\1\0\1\167\7\0\3\167"+
    "\1\147\17\0\7\167\11\0\1\170\1\53\1\121\2\0"+
    "\3\170\1\61\1\62\1\63\7\0\1\63\1\61\1\0"+
    "\1\121\17\0\3\170\1\53\1\170\1\64\12\0\1\171"+
    "\1\53\1\121\2\0\3\171\1\61\1\62\1\63\7\0"+
    "\1\63\1\61\1\0\1\121\17\0\3\171\1\53\1\171"+
    "\1\64\12\0\2\12\1\54\2\0\3\12\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\54\17\0\3\12"+
    "\1\172\1\12\1\64\12\0\2\173\1\147\1\0\5\173"+
    "\1\0\1\173\7\0\3\173\1\147\17\0\7\173\11\0"+
    "\1\174\1\53\1\121\2\0\3\174\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\121\17\0\3\174\1\53"+
    "\1\174\1\64\12\0\1\175\1\53\1\121\2\0\3\175"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\121"+
    "\17\0\3\175\1\53\1\175\1\64\12\0\2\12\1\54"+
    "\2\0\1\176\2\12\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\54\17\0\5\12\1\64\12\0\2\177"+
    "\1\147\1\0\5\177\1\0\1\177\7\0\3\177\1\147"+
    "\17\0\7\177\11\0\1\200\1\53\1\121\2\0\3\200"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\121"+
    "\17\0\3\200\1\53\1\200\1\64\12\0\1\201\1\53"+
    "\1\121\2\0\3\201\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\121\17\0\3\201\1\53\1\201\1\64"+
    "\12\0\2\12\1\54\2\0\3\12\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\54\17\0\4\12\1\202"+
    "\1\64\12\0\2\203\1\147\1\0\5\203\1\0\1\203"+
    "\7\0\3\203\1\147\17\0\7\203\11\0\1\204\1\53"+
    "\1\121\2\0\3\204\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\121\17\0\3\204\1\53\1\204\1\64"+
    "\12\0\1\205\1\53\1\121\2\0\3\205\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\121\17\0\3\205"+
    "\1\53\1\205\1\64\12\0\2\12\1\54\2\0\3\12"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\54"+
    "\17\0\1\12\1\206\3\12\1\64\12\0\2\207\1\147"+
    "\1\0\5\207\1\0\1\207\7\0\3\207\1\147\17\0"+
    "\7\207\11\0\1\210\1\53\1\121\2\0\3\210\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\210\1\53\1\210\1\64\12\0\1\211\1\53\1\121"+
    "\2\0\3\211\1\61\1\62\1\63\7\0\1\63\1\61"+
    "\1\0\1\121\17\0\3\211\1\53\1\211\1\64\12\0"+
    "\2\12\1\54\2\0\3\12\1\61\1\62\1\63\7\0"+
    "\1\63\1\61\1\0\1\54\17\0\3\12\1\212\1\12"+
    "\1\64\12\0\2\213\1\147\1\0\5\213\1\0\1\213"+
    "\7\0\3\213\1\147\17\0\7\213\11\0\1\214\1\53"+
    "\1\121\2\0\3\214\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\121\17\0\3\214\1\53\1\214\1\64"+
    "\12\0\1\215\1\53\1\121\2\0\3\215\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\121\17\0\3\215"+
    "\1\53\1\215\1\64\12\0\2\216\1\147\1\0\5\216"+
    "\1\0\1\216\7\0\3\216\1\147\17\0\7\216\11\0"+
    "\1\217\1\53\1\121\2\0\3\217\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\121\17\0\3\217\1\53"+
    "\1\217\1\64\12\0\1\220\1\53\1\121\2\0\3\220"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\121"+
    "\17\0\3\220\1\53\1\220\1\64\12\0\2\221\1\147"+
    "\1\0\5\221\1\0\1\221\7\0\3\221\1\147\17\0"+
    "\7\221\11\0\1\222\1\53\1\121\2\0\3\222\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\222\1\53\1\222\1\64\12\0\1\223\1\53\1\121"+
    "\2\0\3\223\1\61\1\62\1\63\7\0\1\63\1\61"+
    "\1\0\1\121\17\0\3\223\1\53\1\223\1\64\12\0"+
    "\2\224\1\147\1\0\5\224\1\0\1\224\7\0\3\224"+
    "\1\147\17\0\7\224\11\0\1\225\1\53\1\121\2\0"+
    "\3\225\1\61\1\62\1\63\7\0\1\63\1\61\1\0"+
    "\1\121\17\0\3\225\1\53\1\225\1\64\12\0\1\226"+
    "\1\53\1\121\2\0\3\226\1\61\1\62\1\63\7\0"+
    "\1\63\1\61\1\0\1\121\17\0\3\226\1\53\1\226"+
    "\1\64\12\0\2\227\1\147\1\0\5\227\1\0\1\227"+
    "\7\0\3\227\1\147\17\0\7\227\11\0\1\230\1\53"+
    "\1\121\2\0\3\230\1\61\1\62\1\63\7\0\1\63"+
    "\1\61\1\0\1\121\17\0\3\230\1\53\1\230\1\64"+
    "\12\0\1\231\1\53\1\121\2\0\3\231\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\121\17\0\3\231"+
    "\1\53\1\231\1\64\12\0\2\232\1\147\1\0\5\232"+
    "\1\0\1\232\7\0\3\232\1\147\17\0\7\232\11\0"+
    "\1\233\1\53\1\121\2\0\3\233\1\61\1\62\1\63"+
    "\7\0\1\63\1\61\1\0\1\121\17\0\3\233\1\53"+
    "\1\233\1\64\12\0\1\234\1\53\1\121\2\0\3\234"+
    "\1\61\1\62\1\63\7\0\1\63\1\61\1\0\1\121"+
    "\17\0\3\234\1\53\1\234\1\64\12\0\2\235\1\147"+
    "\1\0\5\235\1\0\1\235\7\0\3\235\1\147\17\0"+
    "\7\235\11\0\1\236\1\53\1\121\2\0\3\236\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\236\1\53\1\236\1\64\14\0\1\147\22\0\1\147"+
    "\37\0\1\237\1\53\1\121\2\0\3\237\1\61\1\62"+
    "\1\63\7\0\1\63\1\61\1\0\1\121\17\0\3\237"+
    "\1\53\1\237\1\64\12\0\1\240\1\53\1\121\2\0"+
    "\3\240\1\61\1\62\1\63\7\0\1\63\1\61\1\0"+
    "\1\121\17\0\3\240\1\53\1\240\1\64\12\0\1\241"+
    "\1\53\1\121\2\0\3\241\1\61\1\62\1\63\7\0"+
    "\1\63\1\61\1\0\1\121\17\0\3\241\1\53\1\241"+
    "\1\64\12\0\1\242\1\53\1\121\2\0\3\242\1\61"+
    "\1\62\1\63\7\0\1\63\1\61\1\0\1\121\17\0"+
    "\3\242\1\53\1\242\1\64\12\0\2\53\1\121\2\0"+
    "\3\53\1\61\1\62\1\63\7\0\1\63\1\61\1\0"+
    "\1\121\17\0\5\53\1\64\2\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[5936];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unkown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\3\0\1\11\1\1\1\11\6\1\2\11\2\1\15\11"+
    "\3\1\2\11\3\1\1\11\2\1\1\0\2\1\1\11"+
    "\1\0\3\1\1\11\1\1\1\0\1\11\1\1\1\0"+
    "\3\1\1\11\2\1\11\11\12\1\1\0\1\11\5\1"+
    "\1\0\3\1\1\11\1\0\1\11\1\0\11\11\37\1"+
    "\1\0\3\1\1\0\2\1\1\0\2\1\1\0\2\1"+
    "\1\0\2\1\1\0\2\1\1\0\2\1\1\0\5\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[162];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true <=> the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true <=> the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;

  /* user code: */
  StringBuffer string = new StringBuffer();

//  int yyline;
//  int yycolumn;

  private LiteralElement symbol(LiteralElementTypes type) {
    return new LiteralElement(type, yyline+1, yycolumn+1);
  }

  private LiteralElement symbol(LiteralElementTypes type, Object value) {
    return new LiteralElement(type, yyline+1, yycolumn+1, value);
  }

  /*
   * assumes correct representation of a long value for
   * specified radix in scanner buffer from <code>start</code>
   * to <code>end</code>
   */
  private long parseLong(int start, int end, int radix) {
    long result = 0;
    long digit;

    for (int i = start; i < end; i++) {
      digit  = Character.digit(yycharat(i),radix);
      result*= radix;
      result+= digit;
    }

    return result;
  }


    private LiteralElement lastToken;
    public LiteralElement nextTokenBuffered() throws java.io.IOException {
        if (lastToken != null) {
            final LiteralElement result = lastToken;
            lastToken = null;
            return result;
        }
        else {
            return nextToken();
        }
    }

    public void pushBack(final LiteralElement token) {
        if (lastToken != null)
            throw new IllegalStateException();
        else
            lastToken = token;
    }


  /**
   * Creates a new scanner
   * There is also a java.io.InputStream version of this constructor.
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public Scanner(java.io.Reader in) {
    this.zzReader = in;
  }

  /**
   * Creates a new scanner.
   * There is also java.io.Reader version of this constructor.
   *
   * @param   in  the java.io.Inputstream to read input from.
   */
  public Scanner(java.io.InputStream in) {
    this(new java.io.InputStreamReader(in));
  }

  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x10000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 2266) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzCurrentPos*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
    }

    /* finally: fill the buffer with new input */
    int numRead = zzReader.read(zzBuffer, zzEndRead,
                                            zzBuffer.length-zzEndRead);

    if (numRead > 0) {
      zzEndRead+= numRead;
      return false;
    }
    // unlikely but not impossible: read 0 characters, but not at end of stream    
    if (numRead == 0) {
      int c = zzReader.read();
      if (c == -1) {
        return true;
      } else {
        zzBuffer[zzEndRead++] = (char) c;
        return false;
      }     
    }

	// numRead < 0
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public neutrino.parser.LiteralElement nextToken() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      for (zzCurrentPosL = zzStartRead; zzCurrentPosL < zzMarkedPosL;
                                                             zzCurrentPosL++) {
        switch (zzBufferL[zzCurrentPosL]) {
        case '\u000B':
        case '\u000C':
        case '\u0085':
        case '\u2028':
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn++;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL)
            zzInput = zzBufferL[zzCurrentPosL++];
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = zzBufferL[zzCurrentPosL++];
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          int zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
        case 44: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\"'));
          }
        case 56: break;
        case 2: 
          { /* ignore */
          }
        case 57: break;
        case 27: 
          { return symbol(LONG_LITERAL, new Long(yytext().subSequence(0,yylength()-1).toString()));
          }
        case 58: break;
        case 19: 
          { return symbol(GT);
          }
        case 59: break;
        case 37: 
          { string.append( '\f' );
          }
        case 60: break;
        case 20: 
          { return symbol(LT);
          }
        case 61: break;
        case 18: 
          { return symbol(POUND);
          }
        case 62: break;
        case 48: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\r'));
          }
        case 63: break;
        case 46: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\\'));
          }
        case 64: break;
        case 38: 
          { string.append( '\b' );
          }
        case 65: break;
        case 5: 
          { return symbol(DOT);
          }
        case 66: break;
        case 29: 
          { return symbol(DOUBLE_LITERAL, new Double(yytext().subSequence(0,yylength()-1).toString()));
          }
        case 67: break;
        case 4: 
          { return symbol(INTEGER_LITERAL, new Integer(yytext()));
          }
        case 68: break;
        case 12: 
          { return symbol(LBRACK);
          }
        case 69: break;
        case 16: 
          { return symbol(COMMA);
          }
        case 70: break;
        case 51: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\n'));
          }
        case 71: break;
        case 35: 
          { string.append( '\t' );
          }
        case 72: break;
        case 15: 
          { return symbol(SEMICOLON);
          }
        case 73: break;
        case 54: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(false));
          }
        case 74: break;
        case 8: 
          { return symbol(LPAREN);
          }
        case 75: break;
        case 42: 
          { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(2, yylength(), 16)));
          }
        case 76: break;
        case 33: 
          { string.append( '\'' );
          }
        case 77: break;
        case 11: 
          { return symbol(RBRACE);
          }
        case 78: break;
        case 41: 
          { return symbol(LONG_LITERAL, new Long(parseLong(0, yylength()-1, 8)));
          }
        case 79: break;
        case 22: 
          { throw new RuntimeException("Unterminated string at end of line");
          }
        case 80: break;
        case 49: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\f'));
          }
        case 81: break;
        case 3: 
          { return symbol(IDENTIFIER, yytext());
          }
        case 82: break;
        case 43: 
          { yybegin(YYINITIAL);
			                              int val = Integer.parseInt(yytext().substring(1,yylength()-1),8);
			                            return symbol(CHARACTER_LITERAL, new Character((char)val));
          }
        case 83: break;
        case 50: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\b'));
          }
        case 84: break;
        case 47: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\t'));
          }
        case 85: break;
        case 17: 
          { return symbol(AT);
          }
        case 86: break;
        case 45: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character('\''));
          }
        case 87: break;
        case 32: 
          { string.append( '\"' );
          }
        case 88: break;
        case 13: 
          { return symbol(RBRACK);
          }
        case 89: break;
        case 52: 
          { return symbol(LONG_LITERAL, new Long(parseLong(2, yylength()-1, 16)));
          }
        case 90: break;
        case 26: 
          { return symbol(DOUBLE_LITERAL, new Double(yytext().toString()));
          }
        case 91: break;
        case 53: 
          { return symbol(BOOLEAN_LITERAL, new Boolean(true));
          }
        case 92: break;
        case 24: 
          { throw new RuntimeException("Unterminated character literal at end of line");
          }
        case 93: break;
        case 9: 
          { return symbol(RPAREN);
          }
        case 94: break;
        case 36: 
          { string.append( '\r' );
          }
        case 95: break;
        case 6: 
          { yybegin(STRING); string.setLength(0);
          }
        case 96: break;
        case 34: 
          { string.append( '\\' );
          }
        case 97: break;
        case 14: 
          { return symbol(COLON);
          }
        case 98: break;
        case 55: 
          { return symbol(INTEGER_LITERAL, new Integer(Integer.MIN_VALUE));
          }
        case 99: break;
        case 1: 
          { throw new RuntimeException("Illegal character \""+yytext()+
                                                              "\" at line "+yyline+", column "+yycolumn);
          }
        case 100: break;
        case 39: 
          { string.append( '\n' );
          }
        case 101: break;
        case 10: 
          { return symbol(LBRACE);
          }
        case 102: break;
        case 28: 
          { return symbol(FLOAT_LITERAL, new Float(yytext().subSequence(0,yylength()-1).toString()));
          }
        case 103: break;
        case 23: 
          { yybegin(YYINITIAL); return symbol(STRING_LITERAL, string.toString());
          }
        case 104: break;
        case 31: 
          { char val = (char) Integer.parseInt(yytext().subSequence(1, yylength()).toString(),8);
                        				   string.append( val );
          }
        case 105: break;
        case 25: 
          { return symbol(INTEGER_LITERAL, new Integer((int) parseLong(0, yylength(), 8)));
          }
        case 106: break;
        case 21: 
          { string.append( yytext() );
          }
        case 107: break;
        case 30: 
          { throw new RuntimeException("Illegal escape sequence \""+yytext()+"\"");
          }
        case 108: break;
        case 40: 
          { yybegin(YYINITIAL); return symbol(CHARACTER_LITERAL, new Character(yytext().charAt(0)));
          }
        case 109: break;
        case 7: 
          { yybegin(CHARLITERAL);
          }
        case 110: break;
        default: 
          if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
            zzAtEOF = true;
            switch (zzLexicalState) {
            case CHARLITERAL: {
              throw new RuntimeException("Unclosed character literal at end of file");
            }
            case 163: break;
            default:
              {
                return symbol(EOF);
              }
            }
          } 
          else {
            zzScanError(ZZ_NO_MATCH);
          }
      }
    }
  }


}
